[profile.default]
remappings = [
    "src/=src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "solidity-mmr/=lib/solidity-mmr/src/",
    "@optimism/libraries=src/lib/external",
]
out = 'out'
libs = ['lib']
ffi = true
viaIR = true
solc = "0.8.20"
evm_version = "shanghai"

[rpc_endpoints]
sepolia = "https://sepolia.drpc.org"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
